2023-07-21 14:32:47.531 [error] <0.276.0> gen_server <0.276.0> terminated with reason: socket_closed_unexpectedly
2023-07-21 14:32:47.531 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 1241
2023-07-21 14:32:47.531 [error] <0.274.0> Supervisor {<0.274.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.275.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.276.0> exit with reason socket_closed_unexpectedly in context child_terminated
2023-07-21 14:32:47.532 [error] <0.274.0> Supervisor {<0.274.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.275.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
